# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

repos:
-   repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 2.7.3
    hooks:
    -   id: editorconfig-checker
        alias: ec
        args: ["-disable-indent-size"]

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v16.0.6
    hooks:
    -   id: clang-format
