[project]
name = "cps-config"
version = "0.0.1"
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
format = "pre-commit run -a"
setup = "meson setup build"
build = { cmd = "ninja", cwd = "build" }
test = { cmd = "ninja test", cwd = "build" }

[dependencies]
python = "3.12.*"
ninja = ">=1.11.1,<1.12"
meson = ">=1.3.2,<1.4"
cxx-compiler = ">=1.7.0,<1.8"
pre-commit = ">=3.6.2,<3.7"
