# This is a basic workflow to help you get started with Actions

name: Ubuntu Latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  meson:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cfg:
          - { id: gcc, cc: gcc, cpp: g++, setup_options: null}
          - { id: gcc-sanitize, cc: gcc, cpp: g++, setup_options: "-Db_sanitize=address,undefined"}
          - { id: clang, cc: clang, cpp: clang++, setup_options: null}

    env:
      CC: ccache ${{ matrix.cfg.cc }}
      CXX: ccache ${{ matrix.cfg.cpp }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: apt
        run: |
          sudo apt update
          sudo apt install ccache clang libjsoncpp-dev libexpected-dev cmake libgtest-dev libfmt-dev ninja-build
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.0.5
        with:
          key: ${{ matrix.cfg.id }}
      - uses: BSFishy/meson-build@v1.0.3
        with:
          meson-version: 1.0.0
          setup-options: ${{ matrix.cfg.setup_options }}
          action: test
          directory: builddir